### ISSUE TITLE
Question: Have you launched your own site based on this code?

### ISSUE THREAD

**Issue by ZeroShepherd** [haris989/Python-Flask-Blog#3]
I would like to know if this blog exists on the web? I want to read through it. I have recently started using DJango and am seeing references occasionally to Flask so I would like to know more and when I saw this on your Github I thought I'd ask :)

Thanks!

**Comment by haris989** [comment]
Hi @ZeroShepherd you can go through the code and host of this blog on a server.
I dont have it hosted anywhere as of now. thanks!
